/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : CourseId,
  'name' : string,
  'passingScore' : bigint,
  'lessons' : Array<string>,
  'price' : bigint,
  'courseType' : CourseType,
}
export type CourseId = bigint;
export type CourseType = { 'premium' : null } |
  { 'basic' : null } |
  { 'standard' : null };
export interface DashboardStats {
  'totalStudents' : bigint,
  'totalRevenue' : bigint,
  'totalRegistrations' : bigint,
}
export interface Student {
  'id' : StudentId,
  'name' : string,
  'referredBy' : bigint,
}
export type StudentId = bigint;
export interface _SERVICE {
  'assignBatch' : ActorMethod<[StudentId, string], undefined>,
  'createCourse' : ActorMethod<
    [string, CourseType, bigint, Array<string>, bigint],
    undefined
  >,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getCourse' : ActorMethod<[CourseId], [] | [Course]>,
  'getDashboard' : ActorMethod<[], DashboardStats>,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'processPayment' : ActorMethod<[StudentId, bigint], undefined>,
  'registerStudent' : ActorMethod<[string, bigint], StudentId>,
  'registerStudentForCourse' : ActorMethod<[StudentId, CourseId], undefined>,
  'setAdmin' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];