/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StudentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CourseType = IDL.Variant({
  'premium' : IDL.Null,
  'basic' : IDL.Null,
  'standard' : IDL.Null,
});
export const CourseId = IDL.Nat;
export const Course = IDL.Record({
  'id' : CourseId,
  'name' : IDL.Text,
  'passingScore' : IDL.Nat,
  'lessons' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'courseType' : CourseType,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'name' : IDL.Text,
  'referredBy' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'totalStudents' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'totalRegistrations' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignBatch' : IDL.Func([StudentId, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCourse' : IDL.Func(
      [IDL.Text, CourseType, IDL.Nat, IDL.Vec(IDL.Text), IDL.Nat],
      [],
      [],
    ),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
  'getDashboard' : IDL.Func([], [DashboardStats], ['query']),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processPayment' : IDL.Func([StudentId, IDL.Nat], [], []),
  'registerStudent' : IDL.Func([IDL.Text, IDL.Nat], [StudentId], []),
  'registerStudentForCourse' : IDL.Func([StudentId, CourseId], [], []),
  'setAdmin' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StudentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CourseType = IDL.Variant({
    'premium' : IDL.Null,
    'basic' : IDL.Null,
    'standard' : IDL.Null,
  });
  const CourseId = IDL.Nat;
  const Course = IDL.Record({
    'id' : CourseId,
    'name' : IDL.Text,
    'passingScore' : IDL.Nat,
    'lessons' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'courseType' : CourseType,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'name' : IDL.Text,
    'referredBy' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'totalStudents' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'totalRegistrations' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignBatch' : IDL.Func([StudentId, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCourse' : IDL.Func(
        [IDL.Text, CourseType, IDL.Nat, IDL.Vec(IDL.Text), IDL.Nat],
        [],
        [],
      ),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
    'getDashboard' : IDL.Func([], [DashboardStats], ['query']),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processPayment' : IDL.Func([StudentId, IDL.Nat], [], []),
    'registerStudent' : IDL.Func([IDL.Text, IDL.Nat], [StudentId], []),
    'registerStudentForCourse' : IDL.Func([StudentId, CourseId], [], []),
    'setAdmin' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };