/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Student {
    id: StudentId;
    name: string;
    referredBy: bigint;
}
export type CourseId = bigint;
export interface RegistrationRecord {
    id: bigint;
    status: string;
    latitude?: number;
    paymentStatus: string;
    feCode: string;
    feName: string;
    studentName: string;
    feId: bigint;
    createdAt: string;
    feePlan: string;
    studentPhone: string;
    updatedAt: string;
    longitude?: number;
    schedule: string;
    price: bigint;
    courseName: string;
    courseType: string;
    classLink: string;
    courseId: bigint;
    locationAddress?: string;
    incentiveCalculated: boolean;
    medium: string;
}
export type StudentId = bigint;
export interface DashboardStats {
    totalStudents: bigint;
    totalRevenue: bigint;
    totalRegistrations: bigint;
}
export interface Course {
    id: CourseId;
    name: string;
    passingScore: bigint;
    lessons: Array<string>;
    price: bigint;
    courseType: CourseType;
}
export enum CourseType {
    premium = "premium",
    basic = "basic",
    standard = "standard"
}
export interface backendInterface {
    /**
     * / Add or update a full registration record (called by FE on any device)
     */
    addRegistrationRecord(rec: RegistrationRecord): Promise<void>;
    assignBatch(studentId: StudentId, batch: string): Promise<void>;
    createCourse(name: string, courseType: CourseType, price: bigint, lessons: Array<string>, passingScore: bigint): Promise<void>;
    getAllCourses(): Promise<Array<Course>>;
    /**
     * / Get all registration records (called by admin to see all FE registrations)
     */
    getAllRegistrationRecords(): Promise<Array<RegistrationRecord>>;
    getAllStudents(): Promise<Array<Student>>;
    getCourse(id: CourseId): Promise<Course | null>;
    getDashboard(): Promise<DashboardStats>;
    /**
     * / Get registration records for a specific FE (called by FE to see their own registrations)
     */
    getRegistrationRecordsByFE(feId: bigint): Promise<Array<RegistrationRecord>>;
    getStudent(id: StudentId): Promise<Student | null>;
    processPayment(studentId: StudentId, amount: bigint): Promise<void>;
    registerStudent(name: string, referredBy: bigint): Promise<StudentId>;
    registerStudentForCourse(studentId: StudentId, courseId: CourseId): Promise<void>;
    setAdmin(): Promise<void>;
    /**
     * / Update payment status and approval details for a registration (called by admin)
     */
    updateRegistrationRecord(id: bigint, status: string, paymentStatus: string, classLink: string, schedule: string, updatedAt: string): Promise<void>;
}
import type { Course as _Course, CourseId as _CourseId, CourseType as _CourseType, RegistrationRecord as _RegistrationRecord, Student as _Student } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addRegistrationRecord(arg0: RegistrationRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRegistrationRecord(to_candid_RegistrationRecord_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRegistrationRecord(to_candid_RegistrationRecord_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignBatch(arg0: StudentId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignBatch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignBatch(arg0, arg1);
            return result;
        }
    }
    async createCourse(arg0: string, arg1: CourseType, arg2: bigint, arg3: Array<string>, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0, to_candid_CourseType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0, to_candid_CourseType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async getAllCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRegistrationRecords(): Promise<Array<RegistrationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRegistrationRecords();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRegistrationRecords();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getCourse(arg0: CourseId): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboard(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard();
            return result;
        }
    }
    async getRegistrationRecordsByFE(arg0: bigint): Promise<Array<RegistrationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrationRecordsByFE(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrationRecordsByFE(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: StudentId): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async processPayment(arg0: StudentId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processPayment(arg0, arg1);
            return result;
        }
    }
    async registerStudent(arg0: string, arg1: bigint): Promise<StudentId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(arg0, arg1);
            return result;
        }
    }
    async registerStudentForCourse(arg0: StudentId, arg1: CourseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudentForCourse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudentForCourse(arg0, arg1);
            return result;
        }
    }
    async setAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin();
            return result;
        }
    }
    async updateRegistrationRecord(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRegistrationRecord(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRegistrationRecord(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_CourseType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseType): CourseType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Course_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Course {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationRecord_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationRecord): RegistrationRecord {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : from_candid_Course_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    latitude: [] | [number];
    paymentStatus: string;
    feCode: string;
    feName: string;
    studentName: string;
    feId: bigint;
    createdAt: string;
    feePlan: string;
    studentPhone: string;
    updatedAt: string;
    longitude: [] | [number];
    schedule: string;
    price: bigint;
    courseName: string;
    courseType: string;
    classLink: string;
    courseId: bigint;
    locationAddress: [] | [string];
    incentiveCalculated: boolean;
    medium: string;
}): {
    id: bigint;
    status: string;
    latitude?: number;
    paymentStatus: string;
    feCode: string;
    feName: string;
    studentName: string;
    feId: bigint;
    createdAt: string;
    feePlan: string;
    studentPhone: string;
    updatedAt: string;
    longitude?: number;
    schedule: string;
    price: bigint;
    courseName: string;
    courseType: string;
    classLink: string;
    courseId: bigint;
    locationAddress?: string;
    incentiveCalculated: boolean;
    medium: string;
} {
    return {
        id: value.id,
        status: value.status,
        latitude: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.latitude)),
        paymentStatus: value.paymentStatus,
        feCode: value.feCode,
        feName: value.feName,
        studentName: value.studentName,
        feId: value.feId,
        createdAt: value.createdAt,
        feePlan: value.feePlan,
        studentPhone: value.studentPhone,
        updatedAt: value.updatedAt,
        longitude: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.longitude)),
        schedule: value.schedule,
        price: value.price,
        courseName: value.courseName,
        courseType: value.courseType,
        classLink: value.classLink,
        courseId: value.courseId,
        locationAddress: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.locationAddress)),
        incentiveCalculated: value.incentiveCalculated,
        medium: value.medium
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CourseId;
    name: string;
    passingScore: bigint;
    lessons: Array<string>;
    price: bigint;
    courseType: _CourseType;
}): {
    id: CourseId;
    name: string;
    passingScore: bigint;
    lessons: Array<string>;
    price: bigint;
    courseType: CourseType;
} {
    return {
        id: value.id,
        name: value.name,
        passingScore: value.passingScore,
        lessons: value.lessons,
        price: value.price,
        courseType: from_candid_CourseType_n8(_uploadFile, _downloadFile, value.courseType)
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    basic: null;
} | {
    standard: null;
}): CourseType {
    return "premium" in value ? CourseType.premium : "basic" in value ? CourseType.basic : "standard" in value ? CourseType.standard : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RegistrationRecord>): Array<RegistrationRecord> {
    return value.map((x)=>from_candid_RegistrationRecord_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Array<Course> {
    return value.map((x)=>from_candid_Course_n6(_uploadFile, _downloadFile, x));
}
function to_candid_CourseType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseType): _CourseType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_RegistrationRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationRecord): _RegistrationRecord {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    latitude?: number;
    paymentStatus: string;
    feCode: string;
    feName: string;
    studentName: string;
    feId: bigint;
    createdAt: string;
    feePlan: string;
    studentPhone: string;
    updatedAt: string;
    longitude?: number;
    schedule: string;
    price: bigint;
    courseName: string;
    courseType: string;
    classLink: string;
    courseId: bigint;
    locationAddress?: string;
    incentiveCalculated: boolean;
    medium: string;
}): {
    id: bigint;
    status: string;
    latitude: [] | [number];
    paymentStatus: string;
    feCode: string;
    feName: string;
    studentName: string;
    feId: bigint;
    createdAt: string;
    feePlan: string;
    studentPhone: string;
    updatedAt: string;
    longitude: [] | [number];
    schedule: string;
    price: bigint;
    courseName: string;
    courseType: string;
    classLink: string;
    courseId: bigint;
    locationAddress: [] | [string];
    incentiveCalculated: boolean;
    medium: string;
} {
    return {
        id: value.id,
        status: value.status,
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        paymentStatus: value.paymentStatus,
        feCode: value.feCode,
        feName: value.feName,
        studentName: value.studentName,
        feId: value.feId,
        createdAt: value.createdAt,
        feePlan: value.feePlan,
        studentPhone: value.studentPhone,
        updatedAt: value.updatedAt,
        longitude: value.longitude ? candid_some(value.longitude) : candid_none(),
        schedule: value.schedule,
        price: value.price,
        courseName: value.courseName,
        courseType: value.courseType,
        classLink: value.classLink,
        courseId: value.courseId,
        locationAddress: value.locationAddress ? candid_some(value.locationAddress) : candid_none(),
        incentiveCalculated: value.incentiveCalculated,
        medium: value.medium
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseType): {
    premium: null;
} | {
    basic: null;
} | {
    standard: null;
} {
    return value == CourseType.premium ? {
        premium: null
    } : value == CourseType.basic ? {
        basic: null
    } : value == CourseType.standard ? {
        standard: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
